### ISSUE TITLE
questions about the result images

### ISSUE THREAD

**Issue by mrgreen3325** [yhjo09/SR-LUT#11]
Hello.
Thanks for your work.

**Comment by yhjo09** [comment]
Hi.
That's because of the small kernel size of SR-LUT (Ours-S is 2x2 and the ensemble covers 3x3).
Note the kernel size of bilinear interpolation is 2x2 and bicubic is 4x4.
It may be mitigated by using a larger LUT size or an adaptive kernel shape, and these ideas may improve our method.
