### ISSUE TITLE
Why the output of SRLUT is clipped to [-1,1]?

### ISSUE THREAD

**Issue by BooguTeam** [yhjo09/SR-LUT#12]
In Train_Model_S.py Line 182-184, each output is clip to [-1, 1], then the batch_S is projected to [-2, 2], but the batch_H belongs to [0,1].

Is this right to compute the L1 loss on [-2, 2] and [0, 1] ?

**Comment by yhjo09** [comment]
Hi,
You can clip each output value in [0, 1] and sum them all to generate the final values in [0, 1].
However, generating negative values is necessary to train a highly expressive model with improved PSNR and visual quality.
The possible value range of `batch_S` is [-2, 2] but it is adjusted to the target range [0, 1] during training without any tricks.

**Comment by Harr7y** [comment]
Thanks for the reply.
