### ISSUE TITLE
train stage 1

### ISSUE THREAD

**Issue by hbw945** [yhjo09/SR-LUT#4]
![屏幕截图 2021-10-11 001048(1).png](https://user-images.githubusercontent.com/70196466/136704932-83140e4d-522c-41a7-9d19-c8576d5fc112.png)
这个是1_train_model_s阶段，他大概持续了几个小时也没有反应但也没报错请问它在正常工作么？期待您的回复！

**Comment by yhjo09** [comment]
Hi, hope the problem was resolved.
