### ISSUE TITLE
Cannot reproduce the psnr value on Set14

### ISSUE THREAD

**Issue by gzhcv** [yhjo09/SR-LUT#5]
Hi, i tested the psnr value on Set14 using the lut provided in this repo `Model_S_x4_4bit_int8.npy`, and get the value 26.41, which is different from paper that is 27.01. I used python package PIL to generate low resoultion image of Set14 (bicubic mode). 

So i'm curious about why there is such a big difference. 

Thanks for your sharing, hope for your reply

**Comment by yhjo09** [comment]
Hi,
The PSNR value is from the LR images of Matlab bicubic downsampling, and
PIL's method can be different.
