### ISSUE TITLE
The method to increase the receptive field

### ISSUE THREAD

**Issue by gzhcv** [yhjo09/SR-LUT#6]
Hi,
   The method to increase the receptive filed in this paper, actually, is rotating and padding. I'm trying to use the padding alone to increase the receptive filed, specifcally, padding the original image at (top or down) and (left or right) four times, and ensemble the results. (for example in the picture below, yellow area results will be ensembled). But the performance even obviously worse than the method that do not ensemble. 
   It's strange, have you tried this method? 

![image](https://user-images.githubusercontent.com/19361578/149103246-3e11d401-80d0-4c50-8263-8c41cdba16f1.png)

**Comment by yhjo09** [comment]
Hi.
I have not tried your approach, but I think you should train four different models for each receptive field, instead of training a single model.
