### ISSUE TITLE
hi，@yhjo9 According to the script provided by the warehouse, psnr has been oscillating around 27.5 (about 400,000 times) during the sr-lut training process. Is this the final result that the model can achieve? thanks

### ISSUE THREAD

**Issue by lei-xiong** [yhjo09/SR-LUT#7]
hi，@yhjo9 According to the script provided by the warehouse, psnr has been oscillating around 27.5 (about 400,000 times) during the sr-lut training process. Is this the final result that the model can achieve? thanks

**Comment by lei-xiong** [comment]
> <img alt="@lei-xiong" width="20" height="20" src="https://avatars.githubusercontent.com/u/19525697?s=60&amp;v=4">

**Comment by yhjo09** [comment]
Hi.
You can get a similar result as in the paper if you follow the instruction, or you can use a pretrained weights [Model_S.pth](https://github.com/yhjo09/SR-LUT/blob/master/2_Transfer_to_LUT/Model_S.pth).
